api/urls.py
from django.urls import path

from api.views import productApiView

app_name = 'api'

urlpatterns = [
    path('products/', productApiView, name='products'),
]

inventory/urls.py
from django.urls import path

from inventory.views import ProductCreateView, ProductDeleteView, ProductListView, ProductUpdateView

app_name = 'inventory'

urlpatterns = [
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/create', ProductCreateView.as_view(), name='product-create'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product-update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product-delete'),
]

stockMgt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('stock/', include('stocks.urls', namespace='stocks')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/', include('api.urls', namespace='api')),

     # Login
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),

    # Logout
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Password Change
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Password Reset
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

stocks/urls.py
from django.urls import path

from stocks.views import StockCreateView, StockDeleteView, StockListView, StockUpdateView
from stocks.views import StockDetailView

app_name = 'stocks'

urlpatterns = [
    path('', StockListView.as_view(), name='stock-list'),
    path('create/', StockCreateView.as_view(), name='stock-create'),
    path('update/<int:pk>/', StockUpdateView.as_view(), name='stock-update'),
    path('delete/<int:pk>/', StockDeleteView.as_view(), name='stock-delete'),
    path('detail/<int:pk>/', StockDetailView.as_view(), name='stock-detail'),
]

stocks/models.py
from django.db import models

from inventory.models import Product

# Create your models here.
class Batch(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='batches')
    stock = models.ForeignKey('Stock', on_delete=models.CASCADE, related_name='batches')
    batch_number = models.CharField(max_length=100, null=True)
    quantity = models.PositiveIntegerField()
    time_registered = models.DateTimeField(auto_now_add=True)
    is_expired = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.product.name} - {self.quantity}"


class Stock(models.Model):
    date_registered = models.DateTimeField(auto_now_add=True, null=True)
    date = models.DateField(null=True)

    def __str__(self):
        return f"Date: {self.date}"
    
    def getDate(self):
        return self.date

stocks/forms.py
from django import forms

from stocks.models import Batch, Stock


class BatchModelForm(forms.ModelForm):
    class Meta:
        model = Batch
        fields = '__all__'
        widgets = {
            'product': forms.TextInput(attrs={'list': 'product_datalist'}),
        }


class StockModelForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = '__all__'
        widgets = {
            'date': forms.DateTimeInput(attrs={'type': 'date'}),
        }
    
BatchFormSet = forms.inlineformset_factory(Stock, Batch, form=BatchModelForm, extra=1)

stocks/views.py
from typing import Any, Dict
from django.shortcuts import redirect, render

from django.views.generic import ListView, UpdateView, DeleteView, DetailView, CreateView
from inventory.models import Product
from stocks.forms import BatchFormSet, StockModelForm

from stocks.models import Stock

# Create your views here.
class StockListView(ListView):
    model = Stock
    template_name = "stocks/stock-list.html"


class StockCreateView(CreateView):
    model = Stock
    form_class = StockModelForm
    template_name = "stocks/stock-create.html"
    success_url = 'stocks:stock-list'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['batch_formset'] = BatchFormSet(self.request.POST, prefix='batches')
        else:
            context['products'] = Product.objects.filter(quantity__gte=1)
            context['batch_formset'] = BatchFormSet(prefix='batches')
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        batch_formset = context['batch_formset']
        print(batch_formset)
        if not batch_formset.is_valid():
            return self.render_to_response(self.get_context_data(form=form))
        self.object = form.save()
        batch_formset.instance = self.object
        print(batch_formset)
        batch_formset.save()

        batches = batch_formset.save(commit=False)
        print(batches)
        for batch in batches:
            print(batch)
            batch.product.quantity = int(batch.product.quantity) + int(batch.quantity)
            batch.product.save()
        return redirect(self.get_success_url())


class StockUpdateView(UpdateView):
    model = Stock
    form_class = StockModelForm
    template_name = "stocks/stock-update.html"
    success_url = 'stocks:stock-list'


class StockDeleteView(DeleteView):
    model = Stock
    template_name = "stocks/stock-delete.html"
    success_url = 'stocks:stock-list'


class StockDetailView(DetailView):
    model = Stock
    context_object_name = 'stock'
    template_name = "stocks/stock-detail.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['batch_formset'] = BatchFormSet(self.request.POST, prefix='batches')
        else:
            context['products'] = Product.objects.filter(quantity__gte=1)
            context['batch_formset'] = BatchFormSet(prefix='batches')
            context['stock'] = self.object
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        batch_formset = context['batch_formset']
        if not batch_formset.is_valid():
            return self.render_to_response(self.get_context_data(form=form))
        self.object = form.save()
        batch_formset.instance = self.object
        batch_formset.save()
        return redirect(self.get_success_url())

stocks/templates/stocks/base.html
{% extends 'base.html' %}


{% block slot2 %}
<div class="sticky z-10 top-0 h-16 border-b bg-white lg:py-2.5">
    <div class="px-6 flex items-center justify-between space-x-4 2xl:container">
        <h5 hidden class="text-2xl text-gray-600 font-medium lg:block">Stocks</h5>
        <button class="w-12 h-16 -mr-2 border-r lg:hidden">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 my-auto" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
        </button>
        <div class="flex space-x-4">
            <!--search bar -->
            <div hidden class="md:block">
                <div class="relative flex items-center text-gray-400 focus-within:text-cyan-400">
                    <span class="absolute left-4 h-6 flex items-center pr-3 border-r border-gray-300">
                        <svg xmlns="http://ww50w3.org/2000/svg" class="w-4 fill-current" viewBox="0 0 35.997 36.004">
                            <path id="Icon_awesome-search" data-name="search"
                                d="M35.508,31.127l-7.01-7.01a1.686,1.686,0,0,0-1.2-.492H26.156a14.618,14.618,0,1,0-2.531,2.531V27.3a1.686,1.686,0,0,0,.492,1.2l7.01,7.01a1.681,1.681,0,0,0,2.384,0l1.99-1.99a1.7,1.7,0,0,0,.007-2.391Zm-20.883-7.5a9,9,0,1,1,9-9A8.995,8.995,0,0,1,14.625,23.625Z">
                            </path>
                        </svg>
                    </span>
                    <input type="search" name="leadingIcon" id="leadingIcon" placeholder="Search here"
                        class="w-full pl-14 pr-4 py-2.5 rounded-xl text-sm text-gray-600 outline-none border border-gray-300 focus:border-cyan-300 transition">
                </div>
            </div>
            <!--/search bar -->
            <button aria-label="search"
                class="w-10 h-10 rounded-xl border bg-gray-100 focus:bg-gray-100 active:bg-gray-200 md:hidden">
                <svg xmlns="http://ww50w3.org/2000/svg" class="w-4 mx-auto fill-current text-gray-600"
                    viewBox="0 0 35.997 36.004">
                    <path id="Icon_awesome-search" data-name="search"
                        d="M35.508,31.127l-7.01-7.01a1.686,1.686,0,0,0-1.2-.492H26.156a14.618,14.618,0,1,0-2.531,2.531V27.3a1.686,1.686,0,0,0,.492,1.2l7.01,7.01a1.681,1.681,0,0,0,2.384,0l1.99-1.99a1.7,1.7,0,0,0,.007-2.391Zm-20.883-7.5a9,9,0,1,1,9-9A8.995,8.995,0,0,1,14.625,23.625Z">
                    </path>
                </svg>
            </button>
            <button aria-label="chat"
                class="w-10 h-10 rounded-xl border bg-gray-100 focus:bg-gray-100 active:bg-gray-200">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 m-auto text-gray-600" fill="none"
                    viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
                </svg>
            </button>
            <button aria-label="notification"
                class="w-10 h-10 rounded-xl border bg-gray-100 focus:bg-gray-100 active:bg-gray-200">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 m-auto text-gray-600" viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                        d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z" />
                </svg>
            </button>
        </div>
    </div>
</div>
{% block content %}{% endblock content %}
{% endblock slot2 %}

{% block scriptslot %}
<script>
    const active_selector = '#stocks-link'
</script>
{% block scripts %}{% endblock scripts %}
{% endblock scriptslot %}

stocks/templates/stocks/stock-create.html
{% extends 'stocks/base.html' %} {% load static tailwind_filters %}


{% block content %}
<div>
    <!-- component -->
    <div class="overflow-x-auto">
        <div class="min-w-screen min-h-screen bg-gray-100 flex items-center justify-center font-sans overflow-hidden">
            <div class="w-full lg:w-5/6">
                <div class="flex py-2">
                    <a href="{% url 'stocks:stock-list' %}" class="text-blue-600 font-medium">
                        <i class="fas fa-arrow-left"></i>
                        Back to stock list
                    </a>
                </div>
                <div class="bg-grey-50 shadow-md rounded-xl my-6 p-8">
                    <form method="post" class=" accent-cyan-500">
                        {% csrf_token %}
                        <div class="form mb-8">
                            {{ form|crispy }}
                        </div>
                        <div class="datalist">
                            <datalist id="product_datalist">
                                {% for prod in products %}
                                    <option value="{{ prod.id }}" label="{{ prod.brand }} {{ prod.name }}"></option>
                                {% endfor %}
                            </datalist>
                        </div>
                        {{ batch_formset.management_form }}
                        <div id="batch-formset" class="grid gap-8">
                            {% for form in batch_formset %}
                                <div class="batch-form grid border p-4">
                                    <div class="">{{ form|crispy }}</div>
                                </div>    
                            {% endfor %}
                        </div>
                        <div class="flex gap-4 mt-8">
                            <button type="submit" class="py-2 px-4 bg-cyan-500 rounded-xl">
                                <i class="fas fa-cloud-arrow-up mr-2"></i>Save Stock
                            </button>
                            <button type="button" id="add-batch-btn">
                                <i class="far fa-square-plus mr-2"></i>Add batch
                            </button>
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    stock_create_page = true
    const innerHtml = `<div class="">{{ batch_formset.empty_form|crispy }}</div><button title="Delete batch"
        type="button" class="delete-batch-btn"><i class="far fa-square-minus text-red-600"></i></button>`
</script>
{% endblock scripts %}

stocks/templates/stocks/stock-detail.html
{% extends 'stocks/base.html' %} {% load static tailwind_filters %}


{% block content %}
<div>
    <!-- component -->
    <div class="overflow-x-auto">
        <div class="min-w-screen min-h-screen bg-gray-100 flex items-center justify-center font-sans overflow-hidden">
            <div class="w-full lg:w-5/6">
                <div class="flex py-2">
                    <a href="{% url 'stocks:stock-list' %}" class="text-blue-600 font-medium">
                        <i class="fas fa-arrow-left"></i>
                        Back to list
                    </a>
                </div>
                <div class="grid">
                    <h2 class="text-3xl text-grey-800 font-semibold">{{ stock.date }}</h2>
                </div>
                <div class="bg-white shadow-md rounded my-6">
                    <table class="min-w-max w-full table-auto">
                        <thead>
                            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                                <th class="py-3 px-6 text-left">Batch code</th>
                                <th class="py-3 px-6 text-left">Product</th>
                                <th class="py-3 px-6 text-left">Brand</th>
                                <th class="py-3 px-6 text-left">Quantity</th>
                                <th class="py-3 px-6 text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="text-gray-600 text-sm font-light">
                            {% for batch in stock.batches.all %}
                            <tr class="border-b border-gray-200 hover:bg-gray-100">
                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                    <div class="flex items-center">
                                        <span class="font-medium">{{ batch.batch_number }}</span>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                    <div class="flex items-center">
                                        <span class="font-medium">{{ batch.product.name }}</span>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                    <div class="flex items-center">
                                        <span class="font-medium">{{ batch.product.brand }}</span>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                    <div class="flex items-center">
                                        <span class="font-medium">{{ batch.quantity }}</span>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-right">
                                    <div class="flex item-center justify-end">
                                        <!-- <a href=""
                                            class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                            </svg>
                                        </a> -->
                                        <a href="{% url 'inventory:product-update' batch.product.pk %}"
                                            class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                            </svg>
                                        </a>
                                        <a href="{% url 'inventory:product-delete' batch.product.pk %}"
                                            class="w-4 mr-0 transform hover:text-purple-500 hover:scale-110">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

stocks/templates/stocks/stock-list.html
{% extends 'stocks/base.html' %} {% load static tailwind_filters %}


{% block content %}
<div>
    <!-- component -->
    <div class="overflow-x-auto">
        <div class="min-w-screen min-h-screen bg-gray-100 flex items-center justify-center font-sans overflow-hidden">
            <div class="w-full lg:w-5/6">
                <div class="flex py-2">
                    <a href="{% url 'stocks:stock-create' %}" class="text-blue-600 font-medium">
                        Create a new stock
                        <i class="fas fa-arrow-right"></i>
                    </a>
                </div>
                <div class="bg-white shadow-md rounded my-6">
                    <table class="min-w-max w-full table-auto">
                        <thead>
                            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                                <th class="py-3 px-6 text-left">Stock Date</th>
                                <th class="py-3 px-6 text-left">Batches</th>
                                <th class="py-3 px-6 text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="text-gray-600 text-sm font-light">
                            {% for stock in object_list %}
                            <tr class="border-b border-gray-200 hover:bg-gray-100">
                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                    <div class="flex items-center">
                                        <span class="font-medium">{{ stock.getDate }}</span>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                    <div class="flex items-center">
                                        <span class="font-medium">{{ stock.batches.count }}</span>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-right">
                                    <div class="flex item-center justify-end">
                                        <a href="{% url 'stocks:stock-detail' stock.pk %}"
                                            class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                            </svg>
                                        </a>
                                        <!-- <a href="{% url 'stocks:stock-update' stock.pk %}"
                                            class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                            </svg>
                                        </a> -->
                                        <!-- <a href="{% url 'stocks:stock-delete' stock.pk %}"
                                            class="w-4 mr-0 transform hover:text-purple-500 hover:scale-110">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </a> -->
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

stocks/templates/stocks/stock-update.html
{% extends 'stocks/base.html' %} {% load static tailwind_filters %}


{% block content %}
<div>
    <!-- component -->
    <div class="overflow-x-auto">
        <div class="min-w-screen min-h-screen bg-gray-100 flex items-center justify-center font-sans overflow-hidden">
            <div class="w-full lg:w-5/6">
                <div class="flex py-2">
                    <a href="{% url 'stocks:stock-list' %}" class="text-blue-600 font-medium">
                        <i class="fas fa-arrow-left"></i>
                        Back to stock list
                    </a>
                </div>
                <div class="bg-grey-50 shadow-md rounded-xl my-6 p-8">
                    <form method="post" class=" accent-cyan-500">
                        {% csrf_token %}
                        <div class="form mb-8">
                            {{ form|crispy }}
                        </div>
                        <div class="datalist">
                            <datalist id="product_datalist">
                                {% for prod in products %}
                                <option value="{{ prod.id }}" label="{{ prod.brand }} {{ prod.name }}"></option>
                                {% endfor %}
                            </datalist>
                        </div>
                        {{ batch_formset.management_form }}
                        <div id="batch-formset" class="grid gap-8">
                            {% for form in batch_formset %}
                            <div class="batch-form grid border p-4">
                                <div class="">{{ form|crispy }}</div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="flex gap-4 mt-8">
                            <button type="submit" class="py-2 px-4 bg-cyan-500 rounded-xl">
                                <i class="fas fa-cloud-arrow-up mr-2"></i>Save Stock
                            </button>
                            <button type="button" id="add-batch-btn">
                                <i class="far fa-square-plus mr-2"></i>Add batch
                            </button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    stock_create_page = true
    const innerHtml = `<div class="">{{ batch_formset.empty_form|crispy }}</div><button title="Delete batch"
        type="button" class="delete-batch-btn"><i class="far fa-square-minus text-red-600"></i></button>`
</script>
{% endblock scripts %}