api/urls.py
from django.urls import path

from api.views import productApiView

app_name = 'api'

urlpatterns = [
    path('products/', productApiView, name='products'),
]

orders/urls.py
from django.urls import path

from orders.views import OrderCreateView, OrderDetailView, OrderListView

app_name = 'orders'

urlpatterns = [
    path('', OrderListView.as_view(), name='order-list'),
    path('detail/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('create/', OrderCreateView.as_view(), name='order-create'),
]

stockMgt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('stock/', include('stocks.urls', namespace='stocks')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/', include('api.urls', namespace='api')),

     # Login
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),

    # Logout
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Password Change
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Password Reset
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

orders/models.py
from django.db import models

from inventory.models import Product

# Create your models here.
class Order(models.Model):
	date = models.DateTimeField(auto_now_add=True)
	vat = models.FloatField(max_length=100)
	discount = models.FloatField(max_length=100)
	payment_type = models.CharField(max_length=100)
	payment_status = models.BooleanField(default=True)

	def __str__(self):
		return self.date

	def getDate(self):
		return self.date
	
	def getTotalCost(self):
		total = 0
		for item in self.items.all():
			total += item.total()
		return "UGX {:,.0f}".format(total)


class OrderItem(models.Model):
	order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	quantity = models.IntegerField()
	
	def total(self):
		return self.quantity * self.product.rate

orders/forms.py
from django.forms import ModelForm, inlineformset_factory, DateTimeInput, TextInput

from orders.models import Order, OrderItem

class OrderModelForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        widgets = {
            'date': DateTimeInput(attrs={'type': 'date'}),
        }


class OrderItemModelForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'
        widgets = {
            'product': TextInput(attrs={'list': 'product_datalist'}),
        }
    
OrderItemFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemModelForm, extra=1)

orders/views.py
from django.shortcuts import redirect, render
from django.views.generic import CreateView, ListView, DetailView
from inventory.models import Product
from orders.forms import OrderItemFormSet, OrderModelForm

from orders.models import Order

# Create your views here.
class OrderListView(ListView):
    model = Order
    template_name = "orders/order-list.html"


class OrderDetailView(DetailView):
    model = Order
    context_object_name = 'order'
    template_name = "orders/order-detail.html"


class OrderCreateView(CreateView):
    model = Order
    form_class = OrderModelForm
    template_name = "orders/order-create.html"
    success_url = 'orders:order-list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['orderitem_formset'] = OrderItemFormSet(self.request.POST, prefix='orderitemes')
        else:
            context['products'] = Product.objects.filter(quantity__gte=1)
            context['orderitem_formset'] = OrderItemFormSet(prefix='orderitemes')
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        orderitem_formset = context['orderitem_formset']
        print(orderitem_formset)
        if not orderitem_formset.is_valid():
            return self.render_to_response(self.get_context_data(form=form))
        self.object = form.save()
        orderitem_formset.instance = self.object
        print(orderitem_formset)
        orderitem_formset.save()

        orderitemes = orderitem_formset.save(commit=False)
        for orderitem in orderitemes:
            print(orderitem)
            orderitem.product.quantity = int(orderitem.product.quantity) - int(orderitem.quantity)
            orderitem.product.save()
        return redirect(self.get_success_url())

orders/templates/orders/base.html
{% extends 'base.html' %}


{% block slot2 %}
<div class="sticky z-10 top-0 h-16 border-b bg-white lg:py-2.5">
    <div class="px-6 flex items-center justify-between space-x-4 2xl:container">
        <h5 hidden class="text-2xl text-gray-600 font-medium lg:block">Stocks</h5>
        <button class="w-12 h-16 -mr-2 border-r lg:hidden">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 my-auto" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
        </button>
        <div class="flex space-x-4">
            <!--search bar -->
            <div hidden class="md:block">
                <div class="relative flex items-center text-gray-400 focus-within:text-cyan-400">
                    <span class="absolute left-4 h-6 flex items-center pr-3 border-r border-gray-300">
                        <svg xmlns="http://ww50w3.org/2000/svg" class="w-4 fill-current" viewBox="0 0 35.997 36.004">
                            <path id="Icon_awesome-search" data-name="search"
                                d="M35.508,31.127l-7.01-7.01a1.686,1.686,0,0,0-1.2-.492H26.156a14.618,14.618,0,1,0-2.531,2.531V27.3a1.686,1.686,0,0,0,.492,1.2l7.01,7.01a1.681,1.681,0,0,0,2.384,0l1.99-1.99a1.7,1.7,0,0,0,.007-2.391Zm-20.883-7.5a9,9,0,1,1,9-9A8.995,8.995,0,0,1,14.625,23.625Z">
                            </path>
                        </svg>
                    </span>
                    <input type="search" name="leadingIcon" id="leadingIcon" placeholder="Search here"
                        class="w-full pl-14 pr-4 py-2.5 rounded-xl text-sm text-gray-600 outline-none border border-gray-300 focus:border-cyan-300 transition">
                </div>
            </div>
            <!--/search bar -->
            <button aria-label="search"
                class="w-10 h-10 rounded-xl border bg-gray-100 focus:bg-gray-100 active:bg-gray-200 md:hidden">
                <svg xmlns="http://ww50w3.org/2000/svg" class="w-4 mx-auto fill-current text-gray-600"
                    viewBox="0 0 35.997 36.004">
                    <path id="Icon_awesome-search" data-name="search"
                        d="M35.508,31.127l-7.01-7.01a1.686,1.686,0,0,0-1.2-.492H26.156a14.618,14.618,0,1,0-2.531,2.531V27.3a1.686,1.686,0,0,0,.492,1.2l7.01,7.01a1.681,1.681,0,0,0,2.384,0l1.99-1.99a1.7,1.7,0,0,0,.007-2.391Zm-20.883-7.5a9,9,0,1,1,9-9A8.995,8.995,0,0,1,14.625,23.625Z">
                    </path>
                </svg>
            </button>
            <button aria-label="chat"
                class="w-10 h-10 rounded-xl border bg-gray-100 focus:bg-gray-100 active:bg-gray-200">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 m-auto text-gray-600" fill="none"
                    viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
                </svg>
            </button>
            <button aria-label="notification"
                class="w-10 h-10 rounded-xl border bg-gray-100 focus:bg-gray-100 active:bg-gray-200">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 m-auto text-gray-600" viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                        d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z" />
                </svg>
            </button>
        </div>
    </div>
</div>
{% block content %}{% endblock content %}
{% endblock slot2 %}

{% block scriptslot %}
<script>
    const active_selector = '#orders-link'
</script>
{% block scripts %}{% endblock scripts %}
{% endblock scriptslot %}

orders/templates/orders/order-create.html
{% extends 'orders/base.html' %} {% load static tailwind_filters %}


{% block content %}
<div>
    <!-- component -->
    <div class="overflow-x-auto">
        <div class="min-w-screen min-h-screen bg-gray-100 flex items-center justify-center font-sans overflow-hidden">
            <div class="w-full lg:w-5/6">
                <div class="flex py-2">
                    <a href="{% url 'orders:order-list' %}" class="text-blue-600 font-medium">
                        <i class="fas fa-arrow-left"></i>
                        Back to orders list
                    </a>
                </div>
                <div class="bg-grey-50 shadow-md rounded-xl my-6 p-8">
                    <form method="post" class=" accent-cyan-500">
                        {% csrf_token %}
                        <div class="form mb-8">
                            {{ form|crispy }}
                        </div>
                        <div class="datalist">
                            <datalist id="product_datalist">
                                {% for prod in products %}
                                <option value="{{ prod.id }}" label="{{ prod.brand }} {{ prod.name }}"></option>
                                {% endfor %}
                            </datalist>
                        </div>
                        <div class="p-4">
                            <p>Items</p>
                        </div>
                        {{ orderitem_formset.management_form }}
                        <div id="batch-formset" class="grid gap-8">
                            {% for form in orderitem_formset %}
                            <div class="batch-form grid border p-4">
                                <div class="">{{ form|crispy }}</div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="flex gap-4 mt-8">
                            <button type="submit" class="py-2 px-4 bg-cyan-500 rounded-xl">
                                <i class="fas fa-cloud-arrow-up mr-2"></i>Confirm Order
                            </button>
                            <button type="button" id="add-batch-btn">
                                <i class="far fa-square-plus mr-2"></i>Add item
                            </button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    stock_create_page = true
    const innerHtml = `<div class="">{{ orderitem_formset.empty_form|crispy }}</div><button title="Remove item"
        type="button" class="delete-batch-btn"><i class="far fa-square-minus text-red-600"></i></button>`
</script>
{% endblock scripts %}

orders/templates/orders/order-list.html
{% extends 'orders/base.html' %} {% load static tailwind_filters %}


{% block content %}
<div>
    <!-- component -->
    <div class="overflow-x-auto">
        <div class="min-w-screen min-h-screen bg-gray-100 flex items-center justify-center font-sans overflow-hidden">
            <div class="w-full lg:w-5/6">
                <div class="flex py-2">
                    <a href="{% url 'orders:order-create' %}" class="text-blue-600 font-medium">
                        Create a new order
                        <i class="fas fa-arrow-right"></i>
                    </a>
                </div>
                <div class="bg-white shadow-md rounded my-6">
                    <table class="min-w-max w-full table-auto">
                        <thead>
                            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                                <th class="py-3 px-6 text-left">Order Date</th>
                                <th class="py-3 px-6 text-left">Items</th>
                                <th class="py-3 px-6 text-left">Total Amount</th>
                                <th class="py-3 px-6 text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="text-gray-600 text-sm font-light">
                            {% for order in object_list %}
                            <tr class="border-b border-gray-200 hover:bg-gray-100">
                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                    <div class="flex items-center">
                                        <span class="font-medium">{{ order.getDate }}</span>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                    <div class="flex items-center">
                                        <span class="font-medium">{{ order.items.count }}</span>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                    <div class="flex items-center">
                                        <span class="font-medium">{{ order.getTotalCost }}</span>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-right">
                                    <div class="flex item-center justify-end">
                                        <a href="{% url 'orders:order-detail' order.pk %}"
                                            class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                    d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                            </svg>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}