api/urls.py
from django.urls import path

from api.views import productApiView

app_name = 'api'

urlpatterns = [
    path('products/', productApiView, name='products'),
]

dashboard/urls.py
from django.urls import path

from dashboard.views import HomepageView

app_name = 'dashboard'

urlpatterns = [
    path('', HomepageView.as_view(), name='dashboard'),
]

inventory/urls.py
from django.urls import path

from inventory.views import ProductCreateView, ProductDeleteView, ProductListView, ProductUpdateView

app_name = 'inventory'

urlpatterns = [
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/create', ProductCreateView.as_view(), name='product-create'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product-update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product-delete'),
]

orders/urls.py
from django.urls import path

from orders.views import OrderCreateView, OrderDetailView, OrderListView

app_name = 'orders'

urlpatterns = [
    path('', OrderListView.as_view(), name='order-list'),
    path('detail/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('create/', OrderCreateView.as_view(), name='order-create'),
]

stockMgt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('stock/', include('stocks.urls', namespace='stocks')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/', include('api.urls', namespace='api')),

     # Login
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),

    # Logout
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Password Change
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Password Reset
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

stocks/urls.py
from django.urls import path

from stocks.views import StockCreateView, StockDeleteView, StockListView, StockUpdateView
from stocks.views import StockDetailView

app_name = 'stocks'

urlpatterns = [
    path('', StockListView.as_view(), name='stock-list'),
    path('create/', StockCreateView.as_view(), name='stock-create'),
    path('update/<int:pk>/', StockUpdateView.as_view(), name='stock-update'),
    path('delete/<int:pk>/', StockDeleteView.as_view(), name='stock-delete'),
    path('detail/<int:pk>/', StockDetailView.as_view(), name='stock-detail'),
]

theme/templates/base_components/header.html
{% load static %}

<header class="bg-primary-950 text-primary-100">
   <div class="p-2 flex justify-end">
      <span class="mr-2">Hi:</span>
      <span class="font-bold uppercase">{{ request.user }}</span>
   </div>
</header>

theme/templates/base_components/sidebar.html
{% load static %}
<aside class="ml-[-100%] fixed z-10 top-0 pb-3 px-6 w-full flex flex-col justify-between h-screen border-r bg-white transition duration-300 md:w-4/12 lg:ml-0 lg:w-[25%] xl:w-[20%] 2xl:w-[15%]">
   <div>
      <div class="-mx-6 px-6 py-4">
         <a href="/" title="home">
            <img src="https://tailus.io/sources/blocks/stats-cards/preview/images/logo.svg" class="w-32"
               alt="system logo">
         </a>
      </div>

      <div class="mt-8 text-center">
         <img src="https://tailus.io/sources/blocks/stats-cards/preview/images/second_user.webp" alt=""
            class="w-10 h-10 m-auto rounded-full object-cover lg:w-28 lg:h-28">
         <h5 class="hidden mt-4 text-xl font-semibold text-gray-600 lg:block">{{ user }}</h5>
         <span class="hidden text-gray-400 lg:block">Admin</span>
      </div>

      <ul class="space-y-2 tracking-wide mt-8">
         <li>
            <a id="dashboard-link" href="{% url 'dashboard:dashboard' %}" aria-label="dashboard"
               class="px-4 py-3 flex items-center space-x-4 rounded-md text-gray-600 group">
               <svg class="-ml-1 h-6 w-6" viewBox="0 0 24 24" fill="none">
                  <path
                     d="M6 8a2 2 0 0 1 2-2h1a2 2 0 0 1 2 2v1a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V8ZM6 15a2 2 0 0 1 2-2h1a2 2 0 0 1 2 2v1a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2v-1Z"
                     class="fill-current text-cyan-400 dark:fill-slate-600"></path>
                  <path d="M13 8a2 2 0 0 1 2-2h1a2 2 0 0 1 2 2v1a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2V8Z"
                     class="fill-current text-cyan-200 group-hover:text-cyan-300"></path>
                  <path d="M13 15a2 2 0 0 1 2-2h1a2 2 0 0 1 2 2v1a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-1Z"
                     class="fill-current group-hover:text-sky-300"></path>
               </svg>
               <span class="-mr-1 font-medium">Dashboard</span>
            </a>
         </li>
         <li>
            <a id="inventory-link" href="{% url 'inventory:product-list' %}"
               class="px-4 py-3 flex items-center space-x-4 rounded-md text-gray-600 group">
               <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path class="fill-current text-gray-300 group-hover:text-cyan-300" fill-rule="evenodd"
                     d="M2 6a2 2 0 012-2h4l2 2h4a2 2 0 012 2v1H8a3 3 0 00-3 3v1.5a1.5 1.5 0 01-3 0V6z"
                     clip-rule="evenodd" />
                  <path class="fill-current text-gray-600 group-hover:text-cyan-600"
                     d="M6 12a2 2 0 012-2h8a2 2 0 012 2v2a2 2 0 01-2 2H2h2a2 2 0 002-2v-2z" />
               </svg>
               <span class="group-hover:text-gray-700">Inventory</span>
            </a>
         </li>
         <li>
            <a id="stocks-link" href="{% url 'stocks:stock-list' %}"
               class="px-4 py-3 flex items-center space-x-4 rounded-md text-gray-600 group">
               <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path class="fill-current text-gray-600 group-hover:text-cyan-600" fill-rule="evenodd"
                     d="M2 5a2 2 0 012-2h8a2 2 0 012 2v10a2 2 0 002 2H4a2 2 0 01-2-2V5zm3 1h6v4H5V6zm6 6H5v2h6v-2z"
                     clip-rule="evenodd" />
                  <path class="fill-current text-gray-300 group-hover:text-cyan-300"
                     d="M15 7h1a2 2 0 012 2v5.5a1.5 1.5 0 01-3 0V7z" />
               </svg>
               <span class="group-hover:text-gray-700">Stock</span>
            </a>
         </li>
         <li>
            <a href="#" class="px-4 py-3 flex items-center space-x-4 rounded-md text-gray-600 group">
               <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path class="fill-current text-gray-600 group-hover:text-cyan-600"
                     d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z" />
                  <path class="fill-current text-gray-300 group-hover:text-cyan-300"
                     d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z" />
               </svg>
               <span class="group-hover:text-gray-700">Other data</span>
            </a>
         </li>
         <li>
            <a id="orders-link" href="{% url 'orders:order-list' %}"
               class="px-4 py-3 flex items-center space-x-4 rounded-md text-gray-600 group">
               <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path class="fill-current text-gray-300 group-hover:text-cyan-300"
                     d="M4 4a2 2 0 00-2 2v1h16V6a2 2 0 00-2-2H4z" />
                  <path class="fill-current text-gray-600 group-hover:text-cyan-600" fill-rule="evenodd"
                     d="M18 9H2v5a2 2 0 002 2h12a2 2 0 002-2V9zM4 13a1 1 0 011-1h1a1 1 0 110 2H5a1 1 0 01-1-1zm5-1a1 1 0 100 2h1a1 1 0 100-2H9z"
                     clip-rule="evenodd" />
               </svg>
               <span class="group-hover:text-gray-700">Orders</span>
            </a>
         </li>
      </ul>
   </div>

   <div class="px-6 -mx-6 pt-4 flex justify-between items-center border-t">
      <button class="px-4 py-3 flex items-center space-x-4 rounded-md text-gray-600 group">
         <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
               d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
         </svg>
         <span class="group-hover:text-gray-700">Logout</span>
      </button>
   </div>
</aside>